CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(50)                             NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE faculty
(
    email      VARCHAR(255) NOT NULL,
    department SMALLINT     NOT NULL,
    CONSTRAINT pk_faculty PRIMARY KEY (email)
);

CREATE TABLE students
(
    email     VARCHAR(255) NOT NULL,
    studentid VARCHAR(255) NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (email)
);

CREATE TABLE users
(
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(500) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (email)
);

ALTER TABLE authorities
    ADD CONSTRAINT uc_f20d24550dbeb24a0e085a630 UNIQUE (email, authority);

ALTER TABLE students
    ADD CONSTRAINT uc_students_studentid UNIQUE (studentid);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);

ALTER TABLE faculty
    ADD CONSTRAINT FK_FACULTY_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_EMAIL FOREIGN KEY (email) REFERENCES users (email);