create table users
(
    email      varchar(255) not null
        constraint pk_users
            primary key,
    password   varchar(500) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    phone      varchar(255) not null
);

create table authorities
(
    id        bigint generated by default as identity
        constraint pk_authorities
            primary key,
    authority varchar(50)  not null,
    email     varchar(255) not null
        constraint fk_authorities_on_email
            references users,
    constraint uc_f20d24550dbeb24a0e085a630
        unique (email, authority)
);

create table faculty
(
    email      varchar(255) not null
        constraint pk_faculty
            primary key
        constraint fk_faculty_on_email
            references users,
    department smallint     not null
);

create table students
(
    email     varchar(255) not null
        constraint pk_students
            primary key
        constraint fk_students_on_email
            references users,
    studentid varchar(255) not null
        constraint uc_students_studentid
            unique
);

create table requests
(
    id                  serial
        primary key,
    status              text         not null,
    created_at          timestamp default CURRENT_TIMESTAMP,
    created_by          varchar(255) not null
        references users
            on delete cascade,
    approved_at         timestamp,
    approved_by         varchar(255)
        references users,
    course_id           bigint,
    duration            varchar(255),
    end_date            date,
    housing_type        varchar(255),
    reason              varchar(255),
    semester            varchar(255),
    start_date          date,
    request_type        varchar(31),
    type                varchar(50)  not null,
    assigned_department smallint     not null
);

create table comments
(
    id         bigint generated by default as identity
        constraint pk_comments
            primary key,
    request_id integer      not null
        references requests,
    user_id    varchar(255) not null
        constraint fk_comments_on_user
            references users,
    text       varchar(255) not null,
    created_at timestamp    not null
);

